// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSb0SXBE_-pksziaCg7jFW7P9l7Qd6MeU',
    appId: '1:783986784654:web:234a8eeec4880b2c514cdf',
    messagingSenderId: '783986784654',
    projectId: 'appchat-9c4f4',
    authDomain: 'appchat-9c4f4.firebaseapp.com',
    storageBucket: 'appchat-9c4f4.appspot.com',
    measurementId: 'G-1TXVQEBWJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_9gI0y3ehkdS_w57dRBt1T8lEtHlsDQo',
    appId: '1:783986784654:android:0c5160f7c3868814514cdf',
    messagingSenderId: '783986784654',
    projectId: 'appchat-9c4f4',
    storageBucket: 'appchat-9c4f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuODDBT-OR9gXwh4UIKsTf1fgMZWZ5JM',
    appId: '1:783986784654:ios:b7e9d0797e270dbd514cdf',
    messagingSenderId: '783986784654',
    projectId: 'appchat-9c4f4',
    storageBucket: 'appchat-9c4f4.appspot.com',
    iosClientId: '783986784654-39kf6j122ee91an75e5ijpdmfbna23a4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appChat',
  );
}
